const fs   = require("fs");
const path = require("path");

function copyDirRecursive(srcDir, destDir) {
  if (!fs.existsSync(srcDir)) return;
  if (!fs.existsSync(destDir)) fs.mkdirSync(destDir, { recursive: true });
  fs.readdirSync(srcDir, { withFileTypes: true }).forEach((entry) => {
    const srcPath  = path.join(srcDir, entry.name);
    const destPath = path.join(destDir, entry.name);
    if (entry.isDirectory()) copyDirRecursive(srcPath, destPath);
    else fs.copyFileSync(srcPath, destPath);
  });
}

// -- Create dist
if (!fs.existsSync("dist")) fs.mkdirSync("dist");

const sharedNavbarPath = path.join("partials", "navbar.html");
const sharedNavbar = fs.existsSync(sharedNavbarPath)
  ? fs.readFileSync(sharedNavbarPath, "utf8")
  : "";

const syllabusModalsPath = path.join("partials", "syllabus-modals.html");
const syllabusModals = fs.existsSync(syllabusModalsPath)
  ? fs.readFileSync(syllabusModalsPath, "utf8")
  : "";

const syllabusToolbarBtnPath = path.join("partials", "syllabus-toolbar-button.html");
const syllabusToolbarBtn = fs.existsSync(syllabusToolbarBtnPath)
  ? fs.readFileSync(syllabusToolbarBtnPath, "utf8")
  : "";

// -- Generate firebase-config.js from Vercel env vars
const cfg = {
  FIREBASE_API_KEY:            process.env.FIREBASE_API_KEY            || "",
  FIREBASE_AUTH_DOMAIN:        process.env.FIREBASE_AUTH_DOMAIN        || "",
  FIREBASE_PROJECT_ID:         process.env.FIREBASE_PROJECT_ID         || "",
  FIREBASE_STORAGE_BUCKET:     process.env.FIREBASE_STORAGE_BUCKET     || "",
  FIREBASE_MESSAGING_SENDER_ID:process.env.FIREBASE_MESSAGING_SENDER_ID|| "",
  FIREBASE_APP_ID:             process.env.FIREBASE_APP_ID             || "",
  MAIL_SERVICE_URL:            process.env.MAIL_SERVICE_URL            || "",
  MAIL_SERVICE_SECRET:         process.env.MAIL_SERVICE_SECRET         || "",
};

const firebaseConfigContent = `// Auto-generated by build.js - do not edit
window.ENV = {
  FIREBASE_API_KEY:            "${cfg.FIREBASE_API_KEY}",
  FIREBASE_AUTH_DOMAIN:        "${cfg.FIREBASE_AUTH_DOMAIN}",
  FIREBASE_PROJECT_ID:         "${cfg.FIREBASE_PROJECT_ID}",
  FIREBASE_STORAGE_BUCKET:     "${cfg.FIREBASE_STORAGE_BUCKET}",
  FIREBASE_MESSAGING_SENDER_ID:"${cfg.FIREBASE_MESSAGING_SENDER_ID}",
  FIREBASE_APP_ID:             "${cfg.FIREBASE_APP_ID}",
  MAIL_SERVICE_URL:            "${cfg.MAIL_SERVICE_URL}",
  MAIL_SERVICE_SECRET:         "${cfg.MAIL_SERVICE_SECRET}",
};
`;

fs.writeFileSync(path.join("dist", "firebase-config.js"), firebaseConfigContent);
console.log("Generated: dist/firebase-config.js");

// ============================================================
// IGCSE pacing pages — generated from igcse-pacing-template.html
// ============================================================
const AO_MATH = `<option value="AO1">AO1 — Knowledge &amp; techniques</option>
          <option value="AO2">AO2 — Analyse &amp; interpret</option>
          <option value="AO1+AO2">AO1 + AO2 — Both</option>`;
const AO_SCIENCE = `<option value="AO1">AO1 — Knowledge &amp; understanding</option>
          <option value="AO2">AO2 — Handle information &amp; solve problems</option>
          <option value="AO3">AO3 — Experimental skills &amp; investigations</option>
          <option value="AO1+AO2">AO1 + AO2 — Both</option>`;

const IGCSE_SUBJECTS = {
  'igcse-math-pacing.html': {
    pageTitle:    'IGCSE Mathematics Pacing — CentralHub',
    accentVars:   '--accent: #c0392b;\n      --accent-dk: #a93224;\n      --accent-2: #fdf0ef;\n      --red-50: #fff5f5;\n      --red-100: #fee2e2;\n      --red-600: #dc2626;\n      --red-700: #b91c1c;\n      --red-800: #991b1b;\n      --red-900: #7f1d1d;',
    heroGradient: 'linear-gradient(135deg, #450a0a 0%, #7f1d1d 40%, #991b1b 70%, #b91c1c 100%)',
    heroGlow:     'rgba(185,28,28,.4)',
    heroIcon:     '∫',
    heroEyebrow:  'IGCSE Mathematics 0580',
    heroTitle:    'IGCSE Mathematics Pacing',
    heroDesc:     'Manage chapters, topics, and syllabus codes for Years 9–10. Monitor teacher coverage and track pacing by class.',
    aoOptions:    AO_MATH,
    pacingConfig: `{ collection: 'math_pacing', docId: 'year9-10', subjectKey: 'math', syllabusCode: '0580', progressKey: 'statuses', classesField: 'igcse_math_classes', yearA: 'Year 9', yearB: 'Year 10', yearAKey: 'year9', yearBKey: 'year10' }`,
    yearA: 'Year 9', yearB: 'Year 10', yearAKey: 'year9', yearBKey: 'year10',
  },
  'igcse-biology-pacing.html': {
    pageTitle:    'IGCSE Biology Pacing — CentralHub',
    accentVars:   '--accent: #1e7a4a;\n      --accent-dk: #166534;\n      --accent-2: #e9f7ef;',
    heroGradient: 'linear-gradient(135deg, #052e16 0%, #14532d 40%, #166534 70%, #15803d 100%)',
    heroGlow:     'rgba(21,128,61,.4)',
    heroIcon:     '🧬',
    heroEyebrow:  'IGCSE Biology 0610',
    heroTitle:    'IGCSE Biology Pacing',
    heroDesc:     'Manage chapters, topics, and syllabus codes for Years 9–10. Monitor teacher coverage and track pacing by class.',
    aoOptions:    AO_SCIENCE,
    pacingConfig: `{ collection: 'biology_pacing', docId: 'year9-10', subjectKey: 'biology', syllabusCode: '0610', progressKey: 'statuses', classesField: 'igcse_biology_classes', yearA: 'Year 9', yearB: 'Year 10', yearAKey: 'year9', yearBKey: 'year10' }`,
    yearA: 'Year 9', yearB: 'Year 10', yearAKey: 'year9', yearBKey: 'year10',
  },
  'igcse-chemistry-pacing.html': {
    pageTitle:    'IGCSE Chemistry Pacing — CentralHub',
    accentVars:   '--accent: #7c3aed;\n      --accent-dk: #6d28d9;\n      --accent-2: #f5f3ff;',
    heroGradient: 'linear-gradient(135deg, #2e1065 0%, #4c1d95 40%, #5b21b6 70%, #6d28d9 100%)',
    heroGlow:     'rgba(109,40,217,.4)',
    heroIcon:     '⚗',
    heroEyebrow:  'IGCSE Chemistry 0620',
    heroTitle:    'IGCSE Chemistry Pacing',
    heroDesc:     'Manage chapters, topics, and syllabus codes for Years 9–10. Monitor teacher coverage and track pacing by class.',
    aoOptions:    AO_SCIENCE,
    pacingConfig: `{ collection: 'chemistry_pacing', docId: 'year9-10', subjectKey: 'chemistry', syllabusCode: '0620', progressKey: 'statuses', classesField: 'igcse_chemistry_classes', yearA: 'Year 9', yearB: 'Year 10', yearAKey: 'year9', yearBKey: 'year10' }`,
    yearA: 'Year 9', yearB: 'Year 10', yearAKey: 'year9', yearBKey: 'year10',
  },
  'igcse-physics-pacing.html': {
    pageTitle:    'IGCSE Physics Pacing — CentralHub',
    accentVars:   '--accent: #0369a1;\n      --accent-dk: #075985;\n      --accent-2: #f0f9ff;',
    heroGradient: 'linear-gradient(135deg, #0c4a6e 0%, #075985 40%, #0369a1 70%, #0284c7 100%)',
    heroGlow:     'rgba(2,132,199,.4)',
    heroIcon:     '⚛',
    heroEyebrow:  'IGCSE Physics 0625',
    heroTitle:    'IGCSE Physics Pacing',
    heroDesc:     'Manage chapters, topics, and syllabus codes for Years 9–10. Monitor teacher coverage and track pacing by class.',
    aoOptions:    AO_SCIENCE,
    pacingConfig: `{ collection: 'physics_pacing', docId: 'year9-10', subjectKey: 'physics', syllabusCode: '0625', progressKey: 'statuses', classesField: 'igcse_physics_classes', yearA: 'Year 9', yearB: 'Year 10', yearAKey: 'year9', yearBKey: 'year10' }`,
    yearA: 'Year 9', yearB: 'Year 10', yearAKey: 'year9', yearBKey: 'year10',
  },
};

// ============================================================
// Checkpoint pacing pages — generated from igcse-pacing-template.html
// ============================================================
const CHECKPOINT_SUBJECTS = {
  'checkpoint-math-pacing.html': {
    pageTitle:    'Checkpoint Mathematics Pacing — CentralHub',
    accentVars:   '--accent: #c0392b;\n      --accent-dk: #a93224;\n      --accent-2: #fdf0ef;',
    heroGradient: 'linear-gradient(135deg, #450a0a 0%, #7f1d1d 40%, #991b1b 70%, #b91c1c 100%)',
    heroGlow:     'rgba(185,28,28,.4)',
    heroIcon:     '∫',
    heroEyebrow:  'Cambridge Checkpoint Mathematics 0862',
    heroTitle:    'Checkpoint Mathematics Pacing',
    heroDesc:     'Manage chapters, topics, and learning objectives for Years 7–8. Monitor teacher coverage and track pacing by class.',
    aoOptions:    AO_MATH,
    pacingConfig: `{ collection: 'checkpoint_math_pacing', docId: 'year7-8', subjectKey: 'math', syllabusCode: '0862', progressKey: 'checkpoint_math_statuses', classesField: 'checkpoint_math_classes', progressionGrid: true, yearA: 'Year 7', yearB: 'Year 8', yearAKey: 'year7', yearBKey: 'year8' }`,
    yearA: 'Year 7', yearB: 'Year 8', yearAKey: 'year7', yearBKey: 'year8',
  },
  'checkpoint-english-pacing.html': {
    pageTitle:    'Checkpoint English Pacing — CentralHub',
    accentVars:   '--accent: #2980b9;\n      --accent-dk: #1f6fa3;\n      --accent-2: #e8f4fd;',
    heroGradient: 'linear-gradient(135deg, #0c2340 0%, #1a4a7a 40%, #1f6fa3 70%, #2980b9 100%)',
    heroGlow:     'rgba(41,128,185,.4)',
    heroIcon:     '📖',
    heroEyebrow:  'Cambridge Checkpoint English 1111',
    heroTitle:    'Checkpoint English Pacing',
    heroDesc:     'Manage chapters, topics, and learning objectives for Years 7–8. Monitor teacher coverage and track pacing by class.',
    aoOptions:    AO_MATH,
    pacingConfig: `{ collection: 'checkpoint_english_pacing', docId: 'year7-8', subjectKey: 'english', syllabusCode: '1111', progressKey: 'checkpoint_english_statuses', classesField: 'checkpoint_english_classes', progressionGrid: true, yearA: 'Year 7', yearB: 'Year 8', yearAKey: 'year7', yearBKey: 'year8' }`,
    yearA: 'Year 7', yearB: 'Year 8', yearAKey: 'year7', yearBKey: 'year8',
  },
  'checkpoint-science-pacing.html': {
    pageTitle:    'Checkpoint Science Pacing — CentralHub',
    accentVars:   '--accent: #27ae60;\n      --accent-dk: #1e8449;\n      --accent-2: #e9f7ef;',
    heroGradient: 'linear-gradient(135deg, #052e16 0%, #14532d 40%, #166534 70%, #15803d 100%)',
    heroGlow:     'rgba(21,128,61,.4)',
    heroIcon:     '🔬',
    heroEyebrow:  'Cambridge Checkpoint Science 0893',
    heroTitle:    'Checkpoint Science Pacing',
    heroDesc:     'Manage chapters, topics, and learning objectives for Years 7–8. Monitor teacher coverage and track pacing by class.',
    aoOptions:    AO_SCIENCE,
    pacingConfig: `{ collection: 'checkpoint_science_pacing', docId: 'year7-8', subjectKey: 'science', syllabusCode: '0893', progressKey: 'checkpoint_science_statuses', classesField: 'checkpoint_science_classes', progressionGrid: true, yearA: 'Year 7', yearB: 'Year 8', yearAKey: 'year7', yearBKey: 'year8' }`,
    yearA: 'Year 7', yearB: 'Year 8', yearAKey: 'year7', yearBKey: 'year8',
  },
};

// ============================================================
// AS/A-Level pacing pages — generated from igcse-pacing-template.html
// ============================================================
const ASALEVEL_SUBJECTS = {
  'as-alevel-math-pacing.html': {
    pageTitle:    'AS & A Level Mathematics Pacing — CentralHub',
    accentVars:   '--accent: #c0392b;\n      --accent-dk: #a93224;\n      --accent-2: #fdf0ef;',
    heroGradient: 'linear-gradient(135deg, #450a0a 0%, #7f1d1d 40%, #991b1b 70%, #b91c1c 100%)',
    heroGlow:     'rgba(185,28,28,.4)',
    heroIcon:     '∫',
    heroEyebrow:  'Cambridge AS & A Level Mathematics 9709',
    heroTitle:    'AS & A Level Mathematics Pacing',
    heroDesc:     'Manage chapters, topics, and syllabus codes for Years 11–12. Monitor teacher coverage and track pacing by class.',
    aoOptions:    AO_MATH,
    pacingConfig: `{ collection: 'asalevel_math_pacing', docId: 'year11-12', subjectKey: 'math', progressKey: 'asmath_statuses', classesField: 'asalevel_math_classes', yearA: 'Year 11', yearB: 'Year 12', yearAKey: 'year11', yearBKey: 'year12' }`,
    yearA: 'Year 11', yearB: 'Year 12', yearAKey: 'year11', yearBKey: 'year12',
  },
  'as-alevel-biology-pacing.html': {
    pageTitle:    'AS & A Level Biology Pacing — CentralHub',
    accentVars:   '--accent: #1e7a4a;\n      --accent-dk: #166534;\n      --accent-2: #e9f7ef;',
    heroGradient: 'linear-gradient(135deg, #052e16 0%, #14532d 40%, #166534 70%, #15803d 100%)',
    heroGlow:     'rgba(21,128,61,.4)',
    heroIcon:     '🧬',
    heroEyebrow:  'Cambridge AS & A Level Biology 9700',
    heroTitle:    'AS & A Level Biology Pacing',
    heroDesc:     'Manage chapters, topics, and syllabus codes for Years 11–12. Monitor teacher coverage and track pacing by class.',
    aoOptions:    AO_SCIENCE,
    pacingConfig: `{ collection: 'asalevel_biology_pacing', docId: 'year11-12', subjectKey: 'biology', progressKey: 'asbio_statuses', classesField: 'asalevel_biology_classes', yearA: 'Year 11', yearB: 'Year 12', yearAKey: 'year11', yearBKey: 'year12' }`,
    yearA: 'Year 11', yearB: 'Year 12', yearAKey: 'year11', yearBKey: 'year12',
  },
  'as-alevel-chemistry-pacing.html': {
    pageTitle:    'AS & A Level Chemistry Pacing — CentralHub',
    accentVars:   '--accent: #e67e22;\n      --accent-dk: #ca6f1e;\n      --accent-2: #fef5e7;',
    heroGradient: 'linear-gradient(135deg, #431407 0%, #7c2d12 40%, #9a3412 70%, #c2410c 100%)',
    heroGlow:     'rgba(194,65,12,.4)',
    heroIcon:     '⚗',
    heroEyebrow:  'Cambridge AS & A Level Chemistry 9701',
    heroTitle:    'AS & A Level Chemistry Pacing',
    heroDesc:     'Manage chapters, topics, and syllabus codes for Years 11–12. Monitor teacher coverage and track pacing by class.',
    aoOptions:    AO_SCIENCE,
    pacingConfig: `{ collection: 'asalevel_chemistry_pacing', docId: 'year11-12', subjectKey: 'chemistry', progressKey: 'aschem_statuses', classesField: 'asalevel_chemistry_classes', yearA: 'Year 11', yearB: 'Year 12', yearAKey: 'year11', yearBKey: 'year12' }`,
    yearA: 'Year 11', yearB: 'Year 12', yearAKey: 'year11', yearBKey: 'year12',
  },
  'as-alevel-physics-pacing.html': {
    pageTitle:    'AS & A Level Physics Pacing — CentralHub',
    accentVars:   '--accent: #0369a1;\n      --accent-dk: #075985;\n      --accent-2: #f0f9ff;',
    heroGradient: 'linear-gradient(135deg, #0c4a6e 0%, #075985 40%, #0369a1 70%, #0284c7 100%)',
    heroGlow:     'rgba(2,132,199,.4)',
    heroIcon:     '⚛',
    heroEyebrow:  'Cambridge AS & A Level Physics 9702',
    heroTitle:    'AS & A Level Physics Pacing',
    heroDesc:     'Manage chapters, topics, and syllabus codes for Years 11–12. Monitor teacher coverage and track pacing by class.',
    aoOptions:    AO_SCIENCE,
    pacingConfig: `{ collection: 'asalevel_physics_pacing', docId: 'year11-12', subjectKey: 'physics', progressKey: 'asphys_statuses', classesField: 'asalevel_physics_classes', yearA: 'Year 11', yearB: 'Year 12', yearAKey: 'year11', yearBKey: 'year12' }`,
    yearA: 'Year 11', yearB: 'Year 12', yearAKey: 'year11', yearBKey: 'year12',
  },
};

function generateFromPacingTemplate(template, cfg) {
  return template
    .replace('{{PAGE_TITLE}}',    cfg.pageTitle)
    .replace('{{ACCENT_VARS}}',   cfg.accentVars)
    .replace('{{HERO_GRADIENT}}', cfg.heroGradient)
    .replace('{{HERO_GLOW}}',     cfg.heroGlow)
    .replace('{{HERO_ICON}}',     cfg.heroIcon)
    .replace('{{HERO_EYEBROW}}',  cfg.heroEyebrow)
    .replace('{{HERO_TITLE}}',    cfg.heroTitle)
    .replace('{{HERO_DESC}}',     cfg.heroDesc)
    .replace('{{AO_OPTIONS}}',    cfg.aoOptions)
    .replace('{{PACING_CONFIG}}', cfg.pacingConfig)
    .replace(/\{\{YEAR_A_KEY\}\}/g, cfg.yearAKey)
    .replace(/\{\{YEAR_B_KEY\}\}/g, cfg.yearBKey)
    .replace(/\{\{YEAR_A\}\}/g,    cfg.yearA)
    .replace(/\{\{YEAR_B\}\}/g,    cfg.yearB);
}

const igcseTemplate      = fs.readFileSync('igcse-pacing-template.html', 'utf8');
const checkpointTemplate = fs.readFileSync('secondary-checkpoint-pacing-template.html', 'utf8');
const asalevelTemplate   = fs.readFileSync('as-alevel-pacing-template.html', 'utf8');

const generatedPacing = {};
Object.entries(IGCSE_SUBJECTS).forEach(([f, cfg]) => {
  generatedPacing[f] = generateFromPacingTemplate(igcseTemplate, cfg);
});
Object.entries(CHECKPOINT_SUBJECTS).forEach(([f, cfg]) => {
  generatedPacing[f] = generateFromPacingTemplate(checkpointTemplate, cfg);
});
Object.entries(ASALEVEL_SUBJECTS).forEach(([f, cfg]) => {
  generatedPacing[f] = generateFromPacingTemplate(asalevelTemplate, cfg);
});

// -- Copy HTML files
const htmlFiles = [
  "index.html",
  "announcements.html",
  "messageboard.html",
  "schools.html",
  "staff.html",
  "documents.html",
  "login.html",
  "academic-calendar.html",
  "appraisals.html",
  "school-appraisals.html",
  "teacher-appraisals.html",
  "ease-system.html",
  "teaching-progress.html",
  "primary-checkpoint-syllabus.html",
  "secondary-checkpoint-syllabus.html",
  "igcse-syllabus.html",
  "schedule-settings.html",
  "igcse-math-pacing.html",
  "igcse-biology-pacing.html",
  "igcse-chemistry-pacing.html",
  "igcse-physics-pacing.html",
  "checkpoint-math-pacing.html",
  "checkpoint-english-pacing.html",
  "checkpoint-science-pacing.html",
  "as-alevel-math-pacing.html",
  "as-alevel-biology-pacing.html",
  "as-alevel-chemistry-pacing.html",
  "as-alevel-physics-pacing.html",
  "as-alevel-syllabus.html",
  "assessment-management.html",
  "assessments.html",
  "console.html",
  "activities.html",
  "surveys.html",
  "survey-console.html",
  "certificates.html",
  "certificate-verify.html",
  "checklist-admin.html",
  "weekly-checklist.html",
  "feedback-management.html",
  "cambridge-calendar.html",
  "event-calendar.html",
  "curriculum-map.html",
  "national-alignment.html",
  "kpi-admin.html",
  "reports.html",
  "school-visits.html",
  "notifications.html",
  "mail-composer.html",
  "library.html",
  "network-health.html",
  "competency-admin.html",
  "specialist-framework.html",
  "specialist-path.html",
  "specialist-portfolio.html",
  "specialist-certificates.html",
  "orientation-admin.html",
  "page-access.html",
  "rules-viewer.html",
  "design-system.html",
  "cambridge-standards.html",
];

htmlFiles.forEach((file) => {
  let source = generatedPacing[file] || null;
  if (!source) {
    if (!fs.existsSync(file)) return;
    source = fs.readFileSync(file, "utf8");
  }

  // Inject shared-styles.css before the first <style> or </head> tag
  if (!source.includes('shared-styles.css')) {
    const sharedLink = '  <link rel="stylesheet" href="shared-styles.css">\n';
    if (source.includes('<style>') || source.includes('<style ')) {
      source = source.replace(/(\s*<style[\s>])/, `\n${sharedLink}$1`);
    } else {
      source = source.replace('</head>', `${sharedLink}</head>`);
    }
  }

  // Inject shared navbar
  let output = sharedNavbar
    ? source.replace("<!-- SHARED_NAVBAR -->", sharedNavbar)
    : source;
  // Inject shared syllabus modals (Teaching Schedule + toast)
  if (syllabusModals) {
    output = output.replace("<!-- SYLLABUS_MODALS -->", syllabusModals);
  }
  // Inject shared syllabus toolbar button (Teaching Schedule launcher)
  if (syllabusToolbarBtn) {
    output = output.replace("<!-- SYLLABUS_TEACH_SCHED_BTN -->", syllabusToolbarBtn);
  }
  // Phase 4 — inject /cambridge-crossref.js once per page (defer; auto-
  // bootstraps from DOM scan). Skip login + index since they don't render
  // CTS chips. Use lastIndexOf so we target the actual document </body>
  // and not a </body> sitting inside an inline JS template literal
  // (e.g. orientation-admin's print-window builder).
  if (file !== 'login.html' && file !== 'index.html' &&
      !output.includes('cambridge-crossref.js')) {
    const closeIdx = output.lastIndexOf('</body>');
    if (closeIdx >= 0) {
      output = output.slice(0, closeIdx)
        + '<script src="cambridge-crossref.js" defer></script>\n'
        + output.slice(closeIdx);
    }
  }
  fs.writeFileSync(path.join("dist", file), output);
  console.log(`Copied: ${file}`);
});

// -- Copy auth-guard.js
if (fs.existsSync("auth-guard.js")) {
  fs.copyFileSync("auth-guard.js", path.join("dist", "auth-guard.js"));
  console.log("Copied: auth-guard.js");
}

// -- Copy cambridge-crossref.js (Phase 4)
if (fs.existsSync("cambridge-crossref.js")) {
  fs.copyFileSync("cambridge-crossref.js", path.join("dist", "cambridge-crossref.js"));
  console.log("Copied: cambridge-crossref.js");
}

// -- Copy firestore.rules so /rules-viewer can fetch it at runtime.
//    Read-only display; the live enforcement comes from the deployed
//    rules at console.firebase.google.com, this is just the
//    human-readable mirror.
if (fs.existsSync("firestore.rules")) {
  fs.copyFileSync("firestore.rules", path.join("dist", "firestore.rules"));
  console.log("Copied: firestore.rules");
}

// -- Copy static assets
if (fs.existsSync("resources")) {
  copyDirRecursive("resources", "dist/resources");
  console.log("Copied: resources/");
}

// -- Copy calendar-fallback.js
if (fs.existsSync("calendar-fallback.js")) {
  fs.copyFileSync("calendar-fallback.js", path.join("dist", "calendar-fallback.js"));
  console.log("Copied: calendar-fallback.js");
}

// -- Copy shared-styles.css
if (fs.existsSync("shared-styles.css")) {
  fs.copyFileSync("shared-styles.css", path.join("dist", "shared-styles.css"));
  console.log("Copied: shared-styles.css");
}

// -- Copy tokens.css
if (fs.existsSync("tokens.css")) {
  fs.copyFileSync("tokens.css", path.join("dist", "tokens.css"));
  console.log("Copied: tokens.css");
}

// -- Copy partials/*.js shared modules + shared partial CSS
const partialsDistDir = path.join("dist", "partials");
if (!fs.existsSync(partialsDistDir)) fs.mkdirSync(partialsDistDir, { recursive: true });
const partialsAssets = ["pacing-core.js", "syllabus-core.js", "syllabus-styles.css"];
for (const fname of partialsAssets) {
  const src = path.join("partials", fname);
  if (fs.existsSync(src)) {
    fs.copyFileSync(src, path.join(partialsDistDir, fname));
    console.log(`Copied: partials/${fname}`);
  }
}

// -- Summary
console.log("\nBuild completed successfully!");
console.log("Environment variables:");
Object.keys(cfg).forEach((key) => {
  console.log(`  ${key}: ${cfg[key] ? "[SET]" : "[NOT SET - login will fail]"}`);
});
