const fs   = require("fs");
const path = require("path");

function copyDirRecursive(srcDir, destDir) {
  if (!fs.existsSync(srcDir)) return;
  if (!fs.existsSync(destDir)) fs.mkdirSync(destDir, { recursive: true });
  fs.readdirSync(srcDir, { withFileTypes: true }).forEach((entry) => {
    const srcPath  = path.join(srcDir, entry.name);
    const destPath = path.join(destDir, entry.name);
    if (entry.isDirectory()) copyDirRecursive(srcPath, destPath);
    else fs.copyFileSync(srcPath, destPath);
  });
}

// â”€â”€ Create dist â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
if (!fs.existsSync("dist")) fs.mkdirSync("dist");

const sharedNavbarPath = path.join("partials", "navbar.html");
const sharedNavbar = fs.existsSync(sharedNavbarPath)
  ? fs.readFileSync(sharedNavbarPath, "utf8")
  : "";

// â”€â”€ Generate firebase-config.js from Vercel env vars â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
const cfg = {
  FIREBASE_API_KEY:            process.env.FIREBASE_API_KEY            || "",
  FIREBASE_AUTH_DOMAIN:        process.env.FIREBASE_AUTH_DOMAIN        || "",
  FIREBASE_PROJECT_ID:         process.env.FIREBASE_PROJECT_ID         || "",
  FIREBASE_STORAGE_BUCKET:     process.env.FIREBASE_STORAGE_BUCKET     || "",
  FIREBASE_MESSAGING_SENDER_ID:process.env.FIREBASE_MESSAGING_SENDER_ID|| "",
  FIREBASE_APP_ID:             process.env.FIREBASE_APP_ID             || "",
};

const firebaseConfigContent = `// Auto-generated by build.js â€” do not edit
window.ENV = {
  FIREBASE_API_KEY:            "${cfg.FIREBASE_API_KEY}",
  FIREBASE_AUTH_DOMAIN:        "${cfg.FIREBASE_AUTH_DOMAIN}",
  FIREBASE_PROJECT_ID:         "${cfg.FIREBASE_PROJECT_ID}",
  FIREBASE_STORAGE_BUCKET:     "${cfg.FIREBASE_STORAGE_BUCKET}",
  FIREBASE_MESSAGING_SENDER_ID:"${cfg.FIREBASE_MESSAGING_SENDER_ID}",
  FIREBASE_APP_ID:             "${cfg.FIREBASE_APP_ID}",
};
`;

fs.writeFileSync(path.join("dist", "firebase-config.js"), firebaseConfigContent);
console.log("Generated: dist/firebase-config.js");

// â”€â”€ Copy HTML files â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
const htmlFiles = [
  "index.html",
  "announcements.html",
  "messageboard.html",
  "schools.html",
  "staff.html",
  "documents.html",
  "login.html",
  "academic-calendar.html",
  "appraisals.html",
  "school-appraisals.html",
  "teacher-appraisals.html",
  "ease-system.html",
  "academics.html",
  "primary-checkpoint-pacing.html",
  "secondary-checkpoint-pacing.html",
  "igcse-pacing.html",
  "igcse-syllabus.html",
  "igcse-math-admin.html",
  "igcse-math-pacing.html",
  "igcse-biology-pacing.html",
  "igcse-chemistry-pacing.html",
  "igcse-physics-pacing.html",
  "as-alevel-pacing.html",
  "assessment-management.html",
  "assessments.html",
  "console.html",
  "activities.html",
  "surveys.html",
  "survey-console.html",
  "certificates.html",
  "certificate-verify.html",
  "checklist-admin.html",
  "curriculum-map.html",
];

htmlFiles.forEach((file) => {
  if (!fs.existsSync(file)) return;
  let source = fs.readFileSync(file, "utf8");

  // Inject shared-styles.css before the first <style> or </head> tag
  if (!source.includes('shared-styles.css')) {
    const sharedLink = '  <link rel="stylesheet" href="shared-styles.css">\n';
    if (source.includes('<style>') || source.includes('<style ')) {
      source = source.replace(/(\s*<style[\s>])/, `\n${sharedLink}$1`);
    } else {
      source = source.replace('</head>', `${sharedLink}</head>`);
    }
  }

  // Inject shared navbar
  const withSharedNavbar = sharedNavbar
    ? source.replace("<!-- SHARED_NAVBAR -->", sharedNavbar)
    : source;
  fs.writeFileSync(path.join("dist", file), withSharedNavbar);
  console.log(`Copied: ${file}`);
});

// â”€â”€ Copy auth-guard.js â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
if (fs.existsSync("auth-guard.js")) {
  fs.copyFileSync("auth-guard.js", path.join("dist", "auth-guard.js"));
  console.log("Copied: auth-guard.js");
}

// â”€â”€ Copy static assets â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
if (fs.existsSync("resources")) {
  copyDirRecursive("resources", "dist/resources");
  console.log("Copied: resources/");
}

// â”€â”€ Summary â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
console.log("\nBuild completed successfully!");
console.log("Environment variables:");
Object.keys(cfg).forEach((key) => {
  console.log(`  ${key}: ${cfg[key] ? "[SET]" : "[NOT SET - login will fail]"}`);
});




// Copy calendar-fallback.js
if (fs.existsSync("calendar-fallback.js")) {
  fs.copyFileSync("calendar-fallback.js", path.join("dist", "calendar-fallback.js"));
  console.log("Copied: calendar-fallback.js");
}

// Copy shared-styles.css
if (fs.existsSync("shared-styles.css")) {
  fs.copyFileSync("shared-styles.css", path.join("dist", "shared-styles.css"));
  console.log("Copied: shared-styles.css");
}

// Copy partials/igcse-pacing-core.js
const partialsDistDir = path.join("dist", "partials");
if (!fs.existsSync(partialsDistDir)) fs.mkdirSync(partialsDistDir, { recursive: true });
const pacingCoreJs = path.join("partials", "igcse-pacing-core.js");
if (fs.existsSync(pacingCoreJs)) {
  fs.copyFileSync(pacingCoreJs, path.join(partialsDistDir, "igcse-pacing-core.js"));
  console.log("Copied: partials/igcse-pacing-core.js");
}
